# Generated by Django 5.0.1 on 2024-02-18 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Pais",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        default="", help_text="Nombre pais", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "status_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Estatus",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="",
                        help_text="Descripcion/Nombre del Estatus",
                        max_length=100,
                    ),
                ),
                (
                    "module",
                    models.IntegerField(
                        default=1,
                        help_text="Modulo/Submodulo al cual pertenece el Estatus 1. Sistema, 2. Campaing, 3. Company, 4. Products, 5. Quote, 6. Facturacion",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "state_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Estado",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        default="", help_text="Nombre del estado", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Pais",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.country",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "rol_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Rol",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rol_name",
                    models.CharField(
                        default="", help_text="Nombre del rol", max_length=100
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Permisos default",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "product_category_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Categoria de producto",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        default="", help_text="Nombre de categoria", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="", help_text="Descripcion de la categoria"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "platform_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Plataforma. ej. Abrevius Capacitacion",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        default="",
                        help_text="Nombre de la plataforma/solucion",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "payment_method_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Metodo de pago",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_name",
                    models.CharField(
                        default="",
                        help_text="Nombre del metodo de pago",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="country",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="UUID Estatus",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.status",
            ),
        ),
        migrations.CreateModel(
            name="CompanyType",
            fields=[
                (
                    "company_type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Tipo de empresa",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        default="",
                        help_text="Tipo de empresa, ej. Partner, Individual, Empresa",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanySize",
            fields=[
                (
                    "company_size_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Tamanio de empresa",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "size_name",
                    models.CharField(
                        default="", help_text="Nombre tamanio empresa", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyPhase",
            fields=[
                (
                    "company_phase_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Fase de la empresa",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phase_name",
                    models.CharField(
                        default="",
                        help_text="Nombre de la fase, ej. Prospecto, Lead, Cliente",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "city_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Ciudad",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        default="", help_text="Nombre de la ciudad", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estado",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.state",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignType",
            fields=[
                (
                    "campaign_type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Tipo de campaña",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign_type_name",
                    models.CharField(
                        default="",
                        help_text="Nombre de tipo de campaña",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Fecha creacion"),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha ultima actualizacion"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "business_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Giro de empresa",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        default="",
                        help_text="Descripcion / Nombre de Giro",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeActivity",
            fields=[
                (
                    "type_activity_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Tipo de Actividad",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
    ]
