# Generated by Django 5.0.1 on 2024-02-18 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignCompany",
            fields=[
                (
                    "campaign_company_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Campaign-Company",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_quote",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Monto total cotizado $",
                        max_digits=10,
                    ),
                ),
                (
                    "total_sale",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Monto total vendido $",
                        max_digits=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creacion interna sistema"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de actualizacion interna sistema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignUser",
            fields=[
                (
                    "campaign_user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Campaign-User",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creacion interna sistema"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de actualizacion interna sistema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "campaign_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID campaña",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign_code",
                    models.CharField(
                        default="", help_text="Codigo de campaña", max_length=50
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(
                        default="", help_text="Nombre de campaña", max_length=150
                    ),
                ),
                (
                    "amount_invested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Monto invertido",
                        max_digits=10,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Fecha de inicio"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Fecha de termino"),
                ),
                ("description", models.TextField(default="", help_text="Descripcion")),
                (
                    "goal_total_companies",
                    models.IntegerField(
                        default=0, help_text="Meta Total de empresas a alcanzar"
                    ),
                ),
                (
                    "goal_total_responses",
                    models.IntegerField(
                        default=0, help_text="Meta Cantidad de respuestas"
                    ),
                ),
                (
                    "goal_number_quotes",
                    models.IntegerField(
                        default=0, help_text="Meta Cantidad cotizaciones"
                    ),
                ),
                (
                    "goal_number_sales",
                    models.IntegerField(
                        default=0, help_text="Meta Cantidad de cierres de venta"
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Meta Monto total $",
                        max_digits=10,
                    ),
                ),
                (
                    "total_companies",
                    models.IntegerField(
                        default=0, help_text="Total empresas alcanzadas"
                    ),
                ),
                (
                    "number_quotes_lead",
                    models.IntegerField(
                        default=0, help_text="Cantidad Total cotizaciones Lead"
                    ),
                ),
                (
                    "number_quotes_client",
                    models.IntegerField(
                        default=0, help_text="Cantidad Total cotizaciones Clientes"
                    ),
                ),
                (
                    "amout_quotes_lead",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Total cotizaciones Leads monto $",
                        max_digits=10,
                    ),
                ),
                (
                    "amout_quotes_client",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Total cotizaciones Clientes monto $",
                        max_digits=10,
                    ),
                ),
                (
                    "total_sales",
                    models.IntegerField(
                        default=0, help_text="Cantidad Total ventas cerradas"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Total ventas cerradas monto $",
                        max_digits=10,
                    ),
                ),
                (
                    "average_quote",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Costo promedio por cotizacion monto $",
                        max_digits=10,
                    ),
                ),
                (
                    "average_sales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Costo promedio por venta monto $",
                        max_digits=10,
                    ),
                ),
                (
                    "register_date",
                    models.DateField(
                        blank=True, help_text="Fecha de registro Front", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creacion interna sistema"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de actualizacion interna sistema",
                    ),
                ),
                (
                    "campaign_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Tipo de campaña",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.campaigntype",
                    ),
                ),
            ],
        ),
    ]
