# Generated by Django 5.0.1 on 2024-02-18 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
        ("quotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="UUID usuario",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quoteoption",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="UUID Cotizacion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quotes.quote",
            ),
        ),
        migrations.AddField(
            model_name="quoteoption",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="UUID Estatus",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.status",
            ),
        ),
        migrations.AddField(
            model_name="optionproduct",
            name="quote_option",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="UUID Opcion de la cotizacion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quotes.quoteoption",
            ),
        ),
    ]
