# Generated by Django 5.0.1 on 2024-02-18 04:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "discount_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Descuento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="", help_text="Codigo para identificar", max_length=100
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", help_text="Nombre", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscountScale",
            fields=[
                (
                    "discount_scale_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Escala de descuento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "range_start",
                    models.IntegerField(default=0, help_text="Rango inicial"),
                ),
                ("range_end", models.IntegerField(default=0, help_text="Rango final")),
                (
                    "percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Procentaje descuento",
                        validators=[django.core.validators.MaxValueValidator(99)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Descuento",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.discount",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "price_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Precio",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="", help_text="Codigo para identificar", max_length=100
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Precio $",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Porcentaje de impuesto",
                        validators=[django.core.validators.MaxValueValidator(99)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="", help_text="Moneda, MX", max_length=2),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID Producto",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="", help_text="Codigo de producto", max_length=100
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", help_text="Nombre del producto", max_length=150
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        help_text="Precio",
                        max_digits=10,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, default="", help_text="Link del producto", null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default.png",
                        help_text="Imagen del producto",
                        null=True,
                        upload_to="image_products",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Pais",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.country",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Descuento",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.discount",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Precio",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.price",
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Categoria de producto",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.productcategory",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="UUID Estatus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.status",
                    ),
                ),
            ],
        ),
    ]
